<?php

$skillls = [
    'Engineering and technical Jobs' => [
        'Aerospace Engineering',
        'Automation Engineering',
        'Automotive Engineering',
        'Building, Supply, Safety Services Engineering',
        'Chemical Engineering',
        'Construction Engineering',
        'Construction, Visualising',
        'Dental Technician',
        'Development',
        'Electrical Engineering',
        'Event Technology',
        'Industrial Engineer',
        'Management, Team Leader',
        'Manufacturing Engineering',
        'Materials Science',
        'Mechanical Engineering',
        'Mechatronic',
        'Medical Technology',
        'Opticians, Acoustician',
        'Plastics Engineering',
        'Power Engineering and Environmental Engineering',
        'Process Engineering',
        'Process Management',
        'Project Management',
        'Quality Management',
        'Sales Engineer',
        'Service Technician',
        'Technical Documentation',
        'Tracer',
    ],

    'IT' => [
        'Applications Administration',
        'Consulting, Engineering',
        'Database Administration',
        'Data Processing, Datawarehouse, Business Intelligence',
        'Embedded Systems, Firmware Development',
        'Hardware Design',
        'Helpdesk',
        'Information Systems',
        'Management, Team Leader',
        'Process Management',
        'Project Management',
        'Quality Assurance, Inspection',
        'SAP / ERP Consulting, Development',
        'Security',
        'Software Development',
        'System and Network Administration',
        'Technical Documentation',
        'Training',
        'Web Development',
    ],
    'Sales' => [
        'Customer Service',
        'Estate Agent',
        'Field Service',
        'Inside Sales, Sales Clerks',
        'Management, Team Leader',
        'Medical Representative',
        'Pre-Sales',
        'Sales Assistant',
        'Shop Sales (Trade)',
        'Telesales',
    ],
    'Marketing and Communication' => [
        'CRM, Direct Marketing',
        'Distribution Marketing',
        'Event Marketing',
        'Journalism, Writing',
        'Management, Team Leader',
        'Market Research, Analysis',
        'Marketing Assistant',
        'Marketing Manager',
        'Media Planning, Purchasing',
        'Online Marketing',
        'Product Management',
        'Public Relations, Corporate Communication',
        'Strategic Marketing',
        'Trade Marketing',
    ],
    'Finance' => [
        'Accounts Payable',
        'Accounts Receivable',
        'Assets Accountant',
        'Auditor',
        'Business Analyst',
        'Compliance, Security',
        'Controlling',
        'External Auditing',
        'Financial, Chief Accountant',
        'Group accounting',
        'Management, Team Leader',
        'Mergers & Acquisitions',
        'Payroll Accounting',
        'Process Management',
        'Tax Advisor',
        'Treasury, Cash Management',
    ],
    'Banking, Financial Services and Insurance' => [
        'Analyst',
        'Asset, Fonds Management',
        'Clerk, Insurance Specialists',
        'Compliance, Security',
        'Corporate Banking',
        'Credit Analysis',
        'Insurance Mathematics, Product Development, Statistics',
        'Investment Banking',
        'Investment Consultancy',
        'Management, Team Leader',
        'Mergers & Acquisitions',
        'Monetary Transfers',
        'Private Banking',
        'Stock Exchange Trading',
    ],
    'Purchasing, Materials Administration and Logistics' => [
        'Dispatching',
        'Fleet Management',
        'Management, Team Leader',
        'Manufacturing Logistics',
        'Outbound, Transportation Logistics',
        'Process Management',
        'Procurement Logistics',
        'Purchasing',
        'Supply Chain Management',
        'Warehouse Logistics',
        'Waste Logistics',
    ],
    'HR' => [
        'Administration',
        'Compensation and Benefits',
        'Consulting',
        'Management, Team Leader',
        'Payroll',
        'Personnel Specialist',
        'Recruitment and Selection',
        'Training, Development',
    ],
    'Administration and Secretariat' => [
        'Assistance, Secretarial',
        'Clerk',
        'Office Management',
        'Property Management',
    ],
    'Sciences and Research' => [
        'Bio Technology',
        'Biology',
        'Chemistry',
        'Geosciences',
        'Mathematics',
        'Pharmaceutic',
        'Physics',
        'Research, Laboratory',
    ],
    'Physicians' => [
        'Anaesthesiology',
        'Child and Adolescent Psychiatry',
        'Clinical Research',
        'Dentistry',
        'Ear, Nose, Throat Specialist',
        'General Medicine',
        'Gynaecology',
        'Hygiene Medicine, Environmental Medicine',
        'Internal Medicine',
        'Neurosurgery, Neurology',
        'Occupational Medicine',
        'Oncology',
        'Ophthalmology',
        'Oral, Facial Surgery',
        'Orthopaedics',
        'Pathology',
        'Pediatrics',
        'Psychiatry, Psychotherapy',
        'Radiology',
        'Specialist for Dermatological, Venereal Diseases',
        'Surgery',
        'Urology',
        'Veterinary Medicine',
    ],
    'Nursing, Therapy' => [
        'Anaesthetic, Intensive Care',
        'Dietician',
        'Disability Support Worker',
        'Elderly Care Nurse',
        'Logopaedics',
        'Management, Team Leader',
        'Medical, Ambulant Service',
        'Midwifery',
        'Nursing',
        'Nursing Assistant',
        'Occupational Therapy',
        'Paediatrics Nursing Care',
        'Physical Therapy',
        'Practice Personnel, Medical Support',
        'Psychotherapy',
        'Radiotherapy',
    ],
    'Education and Social Policy' => [
        'Educator',
        'High School',
        'Kindergarten, Preschool',
        'Management, Team Leader',
        'Primary School',
        'Social, Community Work',
        'Training Supervisor',
        'Training, Adult Education',
        'University, Colleges',
        'Vocational School',
    ],
    'Public Sector' => [
        'Armed Forces',
        'Civil Servant Federal Affairs',
        'Civil Servant Foreign Affairs',
        'Fire Brigade',
        'Government Custom and Excise Officers',
        'Local Government Officials',
        'Organizations, Diplomatic Representatives',
        'Police, Prison, Related Work',
    ],
    'Law' => [
        'Administration of Justice (Judges)',
        'Advocacy',
        'Court, Notary, Legal Assistant',
        'Legal Department',
        'Notary',
    ],
    'Design and Architecture' => [
        'Architecture',
        'Fashion Design, Jewelry Design',
        'Graphic Arts and Communication Design',
        'Media, Screen and Web Design',
        'Photography, Video',
        'Product Design, Industrial Design',
        'Theater, Playhouse, Music, Dance',
    ],
    'Manual Work, Service Industry and Manufacturing' => [
        'Beauty, Wellness',
        'Construction Worker',
        'Electrician',
        'Food Manufacturing',
        'Gastronomy, Hotel Industry',
        'Interior Design',
        'Management, Team Leader',
        'Manufacturing, Production',
        'Mechanician',
        'Metal Crafts',
        'Painter, Varnisher',
        'Quality Assurance',
        'Security',
        'Travel, Tourism',
        'Wood Crafts',
    ],
    'Senior Management' => [
        'Assistance',
        'Branch Management',
        'Business Consulting',
        'Business Development',
        'Department, Business Unit Management',
        'Directors, Chief Executives',
        'Team Leader',
    ]
];

