<?php

namespace Tests\Feature;

use App\Models\Image;
use App\Models\JobPreference;
use App\Models\Profile;
use App\Models\Skill;
use App\Models\User;
use App\Profile\UserProfile;
use Database\Seeders\SkillSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class UserProfileTest extends TestCase
{
    use RefreshDatabase;

    public function getProfileDetails()
    {
        $this->seed(SkillSeeder::class);

        return [
            'details' => [
                'phone_number' => '0936689359',
                'location' => [
                    'city' => 'los angeles',
                    'country' => 'usa'
                ],
                'educations' => [
                    [
                        'graduation_year' => 2021,
                        'degree' => 'bachelors',
                        'institution' => 'tishreen university',
                        'study_field' => 'very good'
                    ]
                ],
                'works_experience' => [
                    [
                        'job_title' => 'seo',
                        'company_name' => 'google',
                        'start_date' => '2/2/2010',
                        'end_date' => '2/2/2020',
                        'industry' => 'IT',
                        'job_category' => 'software developer',
                        'job_subcategory' => 'web development',
                        'job_description' => 'it is very easy job to me its very handful',
                    ]
                ],
                'languages' => [
                    'english', 'arabic'
                ],
            ],
            'visible' => true,
            'skills' => Skill::get()->pluck('id')->take(2)->toArray(),

        ];
    }

    public function getAdditionalAttributes()
    {
        return [
            'details' => [
                'educations' => [
                    'graduation_year' => 2015,
                    'degree' => 'master',
                    'institution' => 'tishreen university',
                    'study_field' => 'very good'
                ]
            ],
        ];
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->withoutMiddleware(\Illuminate\Auth\Middleware\Authorize::class);
    }

    /**
     * @test
     */
    public function user_can_store_profile_information()
    {
        $this->actingAs($user = User::factory()->create(), 'api');

        $response = $this->post('/api/users/' . $user->id . '/profile', $this->getProfileDetails())
            ->assertStatus(201);

        $profile = $user->profile;

        $this->assertNotNull($user->profile, 'user profile not found');
        $this->assertInstanceOf(UserProfile::class, $profile->details);
        $response->assertJson(
            [
                'data' => [
                    'type' => 'profile',
                    'id' => $profile->id,
                    'attributes' => [
                        'details' => [
                            'phone_number' => '0936689359',
                            'location' => 'los angeles, usa',
                            'educations' => [
                                [
                                    'graduation_year' => 2021,
                                    'degree' => 'bachelors',
                                    'institution' => 'tishreen university',
                                    'study_field' => 'very good'
                                ]
                            ],
                            'works_experience' => [
                                [
                                    'job_title' => 'seo',
                                    'company_name' => 'google',
                                    'start_date' => '2/2/2010',
                                    'end_date' => '2/2/2020',
                                    'industry' => 'IT',
                                    'job_category' => 'software developer',
                                    'job_subcategory' => 'web development',
                                    'job_description' => 'it is very easy job to me its very handful',
                                ]
                            ],
                            'languages' => [
                                'english', 'arabic'
                            ],
                        ],
                    ]
                ],
                'links' => [
                    'self' => '/api/users/' . $user->id . '/profile'

                ]
            ]
        );
    }

    /**
     * @test
     */
    public function user_can_retrieve_profile_belongs_to_another_user()
    {
        $this->actingAs($profileOwner = User::factory()->create(), 'api');
        $this->post('/api/users/' . $profileOwner->id . '/profile', $this->getProfileDetails())
            ->assertStatus(201);
        $profile = $profileOwner->profile;

        $this->actingAs($user = User::factory()->create(), 'api');
        $response = $this->get('/api/users/' . $profileOwner->id . '/profile')->assertStatus(200);

        $response->assertJson(
            [
                'data' => [
                    'type' => 'profile',
                    'id' => $profile->id,
                    'attributes' => [
                        'details' => [
                            'phone_number' => '0936689359',
                            'location' => 'los angeles, usa',
                            'educations' => [
                                [
                                    'graduation_year' => 2021,
                                    'degree' => 'bachelors',
                                    'institution' => 'tishreen university',
                                    'study_field' => 'very good'
                                ]
                            ],
                            'works_experience' => [
                                [
                                    'job_title' => 'seo',
                                    'company_name' => 'google',
                                    'start_date' => '2/2/2010',
                                    'end_date' => '2/2/2020',
                                    'industry' => 'IT',
                                    'job_category' => 'software developer',
                                    'job_subcategory' => 'web development',
                                    'job_description' => 'it is very easy job to me its very handful',
                                ]
                            ],
                            'languages' => [
                                'english', 'arabic'
                            ],
                        ],
                        'user' => [
                            'data' => [
                                'type' => 'users',
                                'id' => $profileOwner->id,
                                'attributes' => [
                                    'email' => $profileOwner->email,
                                    'name' => $profileOwner->name
                                ],
                            ],
                        ]
                    ]
                ],
                'links' => [
                    'self' => '/api/users/' . $profileOwner->id . '/profile'
                ]
            ]);
    }

    /**
     * @test
     */
    public function user_can_assign_skills_to_his_profile()
    {
        $this->withoutExceptionHandling();
        $this->actingAs($user = User::factory()->create(), 'api');
        $skillIds = $this->getProfileDetails()['skills'];
        $skills = Skill::find($skillIds);

        $response = $this->post('/api/users/' . $user->id . '/profile', $this->getProfileDetails())
            ->assertStatus(201);

        $this->assertNotNull($user->skills, 'there is no skills assigned to the user');
        $this->assertEquals(2, $user->skills()->count());
        $response->assertJsonCount(2, 'data.attributes.skills.data');
        $response->assertJson([
            'data' => [
                'attributes' => [
                    "skills" => [
                        "data" => [
                            [
                                "data" => [
                                    "type" => "skills",
                                    "id" => $skills[0]->id,
                                    "attributes" => [
                                        "name" => $skills[0]->name,
                                        "parent_id" => $skills[0]->parent_id
                                    ]
                                ]
                            ],
                            [
                                "data" =>
                                    [
                                        "type" => "skills",
                                        "id" => $skills[1]->id,
                                        "attributes" =>
                                            [
                                                "name" => $skills[1]->name,
                                                "parent_id" => $skills[1]->parent_id
                                            ]
                                    ]
                            ]
                        ]
                    ]]]]);
    }

    /**
     * @test
     */
    public function user_can_add_additional_details_to_his_profile()
    {
        $this->withoutExceptionHandling();
        $this->actingAs($user = User::factory()->create(), 'api');

        $profile = Profile::factory()->create(['user_id' => $user->id]);

        $educationsCount = sizeof($profile->details->educations) + 1;

        $response = $this->post('/api/users/' . $user->id . '/profile', $this->getAdditionalAttributes())
            ->assertStatus(201);

        $profile = $user->profile;
        $profile->fresh();
        $this->assertNotNull($profile);

        $this->assertCount($educationsCount, $profile->details->educations);
        $this->assertCount(1, Profile::get(), 'there are more one profile for a single user');;
    }


    /**
     * @test
     */
    public function user_can_update_his_profile()
    {
        $this->withoutExceptionHandling();
        $this->actingAs($user = User::factory()->create(), 'api');

        $resp = $this->post('api/users/' . $user->id . './profile', $this->getProfileDetails());


        $profile = json_decode($resp->getContent())->data->attributes;

        $education = $profile->details->educations[0];
        $education->degree = 'DR';

        $location = ['city' => 'new york', 'country' => 'usa'];
        $profile->details->location = $location['country'] . ', ' . $location['city'];

        $work_experience = $profile->details->works_experience[0];
        $work_experience->job_category = 'backend web developer';
        $profile->details->works_experience;


        $storedProfile = $user->profile;
        $storedProfile->details->location = 'usa, new york';
        $storedProfile->details->educations[0]->degree = 'DR';
        $storedProfile->details->works_experience[0]->job_category = 'backend web developer';

        $details = [
            'location' => $location,
            'educations' => [$education],
            'works_experience' => [$work_experience]
        ];

        $this->putJson('/api/users/' . $user->id . '/profile', [

            'details' => $details,
            'visible' => false
        ]);

        $newProfile = $user->profile;

        $this->assertEquals($storedProfile->details->location, $newProfile->details->location);
        $this->assertObjectEquals($storedProfile->details->educations[0], $newProfile->details->educations[0], 'equals');
        $this->assertObjectEquals($storedProfile->details->works_experience[0], $newProfile->details->works_experience[0], 'equals');
        $this->assertObjectEquals($storedProfile->details, $newProfile->details, 'equals');
        $this->assertEquals(false, $newProfile->visible);
    }


    /**
     * @test
     */
    public function user_can_change_his_skills()
    {
        $user = User::factory()->create();
        $this->actingAs($user);
        Profile::factory()->create(['user_id' => $user->id]);
        $skills = Skill::factory()->count(3)->create();

        //test user hasn't have a skills

        $this->putJson('api/users/' . $user->id . '/profile', [
            'skills' =>
                [
                    $skills[0]->id,
                    $skills[1]->id
                ]
        ]);
        $this->assertCount(2, $user->skills);

        $this->assertEquals(
            Skill::find([$skills[0]->id, $skills[1]->id])->pluck('id'),
            $user->skills->pluck('id')
        );

        $user = $user->fresh();

        $this->putJson('api/users/' . $user->id . '/profile', [
            'skills' =>
                [
                    $skills[2]->id,
                ]
        ]);

        $this->assertCount(1, $user->skills);
        $this->assertEquals(
            $skills[2]->id,
            $user->skills->first()->id
        );

    }

    /**
     * @test
     */
    public function user_can_delete_details_from_his_profile()
    {
        $this->withoutExceptionHandling();
        $user = User::factory()->create();
        $this->actingAs($user);
        $profile = Profile::factory()->create(['user_id' => $user->id]);

        $eduShouldDelete = $profile->details->educations[0];

        $eduBeforeDeletion = $user->profile->details->educations;
        $this->assertNotEmpty((collect($eduBeforeDeletion))->where('id', $eduShouldDelete->id)->first());

        $req = [
            'details' => [
                'educations' => [
                    [
                        'id' => $eduShouldDelete->id
                    ]
                ]
            ]];
        $this->put('api/users/' . $user->id . '/profile/delete-details', $req)->assertStatus(200);
        $educations = $user->profile->details->educations;

        $this->assertCount(count($eduBeforeDeletion) - 1, $educations);

        $this->assertEmpty((collect($educations))->where('id', $eduShouldDelete->id)->first());

    }

    /**
     * @test
     */
    public function delete_un_exist_details_should_return_not_found_exception()
    {
        $user = User::factory()->create();
        $this->actingAs($user);
        $profile = Profile::factory()->create(['user_id' => $user->id]);

        $req = [
            'details' => [
                'educations' => [
                    [
                        'id' => '0'
                    ]
                ]
            ]];

        $this->put('api/users/' . $user->id . '/profile/delete-details', $req)->assertStatus(404);
    }

    /**
     * @test
     */
    public function job_preference_retrieved_with_user_profile_resource()
    {
        $user = User::factory()->create();
        $this->actingAs($user);
        Profile::factory()->create(['user_id' => $user->id]);
        $jobPreference = JobPreference::factory()->create(['user_id' => $user->id]);
        $this->get('api/users/' . $user->id . '/profile')->assertStatus(200)
            ->assertJson([
                'included' => [
                    'job_preference' => [
                        'data' => [
                            'id' => $jobPreference->id
                        ]
                    ]
                ]
            ]);
    }

    /**
     * @test
     */
    public function user_image_retrieved_with_user_profile_resource()
    {
        $this->withoutExceptionHandling();
        $this->actingAs($user = User::factory()->create());

        Profile::factory()->create(['user_id' => $user->id]);

        $image = Image::factory()->create(['imageable_id' => $user->id]);

        $resp = $this->get('api/users/' . $user->id . '/profile')->assertStatus(200)
            ->assertJson([
                'included' => [
                    'image' => url($image->path)
                ]
            ]);
    }
}
